### PR TITLE
Allow matching whole file paths

### PR DESCRIPTION
**Pull request by adamczykpiotr**
Hi,
Awesome plugin, especially for scatterbrains like me! 
This PR adds feature of allowing whole path matching (i.e. whether a file from /database/migrations/*.php was changed)

I've build it myself and had it working without a problem.

### CODE REVIEW

**Comment by adamczykpiotr** [comment]
It's worth mentioning that it doesn't unify platform-dependent separators ("/" vs "\\"). It might be something worth adding in the future

**Comment by malochak** [comment]
> It's worth mentioning that it doesn't unify platform-dependent separators ("/" vs "\"). It might be something worth adding in the future

Platforms that use "/" are only the correct ones. 
Just kidding :D

**Comment by btbrq** [comment]
> Hi, Awesome plugin, especially for scatterbrains like me! This PR adds feature of allowing whole path matching (i.e. whether a file from /database/migrations/*.php was changed)
> 
> I've build it myself and had it working without a problem.

Thanks for your contribution :) The idea behind file name only matching comes from Intellij "Find in files" feature, where the IDE lets you only filter the results by file name/extension. But this doesn't have to be the same here, I will check the behaviour of the plugin with your changes during the weekend and merge the PR :)

**Comment by adamczykpiotr** [comment]
Great, thanks! 

To make your life a little bit easier the only change I discovered is that that pre-existing patters not starting with "*" will not work with my changes (as the whole path will not be matched). 

Before releasing this version i would suggest puting a warning in the release notes or perhaps migrating everyone's patterns when updating from previous versions (something like add "*" at the beginning of the pattern string if the first char !== "*")

**Comment by btbrq** [comment]
> Great, thanks!
> 
> To make your life a little bit easier the only change I discovered is that that pre-existing patters not starting with "*" will not work with my changes (as the whole path will not be matched).
> 
> Before releasing this version i would suggest puting a warning in the release notes or perhaps migrating everyone's patterns when updating from previous versions (something like add "_" at the beginning of the pattern string if the first char !== "_")

I guess this should not be the case, if it was not starting with '*' mark, then it would match just exact file name.
Merged. Will deploy newer version shortly. Thanks for the contribution :)

**Comment by btbrq** [comment]
It is live on the platform :)

**Comment by adamczykpiotr** [comment]
Awesome! I'll soon publish laravel checklist and recommend this for everyone in the company I work in.

Thanks again for this magnificent plugin, great idea perfectly excecuted!

**Pull request merged**
